version: "3.4"

services:
  # Kafka brokers are stateless.
  # Zookeeper is responsible for managing the Kafka cluster and also electing the lead broker
  zookeeper:
    image: bitnami/zookeeper
    # If there are any exceptions, it should always restart
    restart: always
    ports:
      - "2181:2181"
    # That would be the directory on the host
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    container_name: "techbankNet_zookeeper"
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
    container_name: "techbankNet_kafka"
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    network_mode: "techbankNet"
    volumes:
      - "mongodb_data:/data/db"
    container_name: "techbankNet_mongodb"
  mysql:
    image: mysql:latest
    restart: always
    network_mode: "techbankNet"
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=techbankRootPsw
    container_name: "techbankNet_mysql"

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data:
    driver: local
  mysql_data:
    driver: local

networks:
  default:
    external:
      name: techbankNet